---
# tasks file for install
- name: Disable CDROM source
  lineinfile:
    dest: "{{ source }}"
    regexp: '^deb cdrom:*'
    line: ''

- name: Install Python3
  apt: 
    name: python3 
    state: latest
 
- name: Install Python3-pip package
  apt: 
    name: python3-pip 
    state: latest

- name: Install Python3-venv package
  apt: 
    name: python3-venv 
    state: latest
 
- name: Install Python3-dev package
  apt: 
    name: python3-dev 
    state: latest   
  
- name: Install rsync
  apt: 
    name: rsync 
    state: latest
  
- name: Install Nginx
  apt: 
    name: nginx 
    state: latest
  notify: start nginx
  
- name: Install uWSGI
  apt: 
    name: uwsgi 
    state: latest
  notify: start uwsgi