version: "3.3"

services:

  flask:
    build: ./Flask
    container_name: Flask-app
    restart: always
    expose:
      - "5555"

  nginx:
    build: ./nginx
    container_name: nginx-server
    restart: always
    ports:
      - "80:8080"
      - "443:44443"
    volumes: 
     - /etc/nginx/ssl/:/etc/nginx/ssl/