---
# tasks for deploy jsonservice
 
- name: Copy app files to the Virtual Machine
  become: no
  copy:
    owner: "{{ user }}"
    group: "{{ user }}"
    dest: "~/{{ app_dest }}"
    src: "app"
  
- name: Set address in Nginx config file
  become: no
  replace: 
    dest: "~/{{ app_dest }}/app/nginx/nginx.conf"
    regexp: '"IP"'
    replace: "{{ address }}"

- name: Create and start services
  docker_compose:
    project_src: "/home/{{ user }}/{{ app_dest }}/app"
    build: yes
  register: output

- debug:
    var: output

- name: Delete intermediate images
  shell:
    cmd: docker image prune -f --filter label=stage=builder
  register: output

- name: Delete unused images
  docker_prune:
    images: yes
    images_filters:
      dangling: true

- debug:
    var: output

- name: Delete app files
  become: no
  file:
    path: "~/{{ app_dest }}"
    state: absent