---
# handlers file for deploy jsonservice

- name: restart uwsgi
  service: 
    name: uwsgi 
    state: restarted

- name: reload nginx
  service: 
    name: nginx 
    state: restarted

- name: start jsonservice
  service: 
    name: jsonservice.service 
    state: started 
    enabled: yes