---
# tasks for deploy jsonservice

- name: Copy app files to the Virtual Machine
  become: no
  copy:
    owner: "{{ user }}"
    group: "{{ user }}"
    dest: "~/{{ app_dest }}"
    src: "app"
  
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
  
- name: Install requirements
  become: no
  pip: 
    virtualenv: "~/{{ app_dest }}/app/env"
    requirements: "~/{{ app_dest }}/app/requirements.txt"
  
- name: Copy Nginx config file
  copy:
    dest: /etc/nginx/sites-available/
    src: config_files/jsonservice
    mode: '0760'
    owner: root
    group: root

- name: Set address in Nginx config file
  replace: 
    dest: /etc/nginx/sites-available/jsonservice
    regexp: '"IP"'
    replace: "{{ address }}"

# -----------SSL CONFIGURATION------------

- name: Create directory for SSL
  file:
    path: /etc/nginx/ssl
    state: directory

# -------AUTO SSL WITHOUT PASSPHRASE------

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: /etc/nginx/ssl/jsonservice.key
  register: generate_ssl_key
  when: 
    - auto_ssl == true
    - ssl_passphrase == false

- name: Generate an SSL certificate on the Virual Machine
  community.crypto.x509_certificate:
    path: /etc/nginx/ssl/jsonservice.crt
    privatekey_path: /etc/nginx/ssl/jsonservice.key
    provider: selfsigned
  when: 
    - auto_ssl == true
    - ssl_passphrase == false

# ---------AUTO SSL WITH PASSPHRASE--------

- name: Generate an OpenSSL private key with passphrase
  openssl_privatekey:
    path: /etc/nginx/ssl/jsonservice.key
    passphrase: "{{ passphrase }}"
    cipher: "{{ cipher }}"
  register: generate_ssl_key
  when: 
    - auto_ssl == true
    - ssl_passphrase == true

- name: Generate an SSL certificate with passphrase on the Virual Machine
  community.crypto.x509_certificate:
    path: /etc/nginx/ssl/jsonservice.crt
    privatekey_passphrase: "{{ passphrase }}"
    privatekey_path: /etc/nginx/ssl/jsonservice.key
    provider: selfsigned
  when: 
    - auto_ssl == true
    - ssl_passphrase == true

# -------AUTO SSL PASSPHRASE CONFIG-------

- name: Create directory for ssl_password_file
  file:
    path: "/etc/nginx/ssl/keys/"
    state: directory
  when: auto_ssl == true

- name: Create an empty ssl_password_file
  file:
    path: "/etc/nginx/ssl/keys/ssl_password_file"
    state: touch
    owner: root
    group: root
    mode: '0400'
  when: auto_ssl == true

- name: Write an SSL passphrase to the ssl_password_file
  copy: 
    content: "{{ passphrase }}"
    dest: "/etc/nginx/ssl/keys/ssl_password_file"
  when: 
    - auto_ssl == true
    - ssl_passphrase == true

- name: Copy SSL key and certificate files to the Virtual Machine
  copy:
    owner: root
    group: root
    mode: '0400'
    dest: "/etc/nginx/"
    src: "ssl"
  when: auto_ssl == false

#  -------END OF SSL CONFIGURATION-------

- name: Copy jsonservie config file
  copy:
    dest: /etc/systemd/system/
    src: config_files/jsonservice.service
    mode: '0760'
    owner: root
    group: root
  notify: start jsonservice

- name: Set path in the service file
  replace: 
    dest: /etc/systemd/system/jsonservice.service
    regexp: '"PATH"'
    replace: "/home/{{user}}/{{ app_dest }}"
    
- name: Set user in the service file
  replace: 
    dest: /etc/systemd/system/jsonservice.service
    regexp: '"USER"'
    replace: "{{ user }}"

- name: Enable site on the Nginx server
  file:
    src: /etc/nginx/sites-available/jsonservice
    dest: /etc/nginx/sites-enabled/jsonservice
    state: link

- name: Restart the jsonservice
  service:
    name: jsonservice
    state: restarted
  notify: reload nginx